# site_name: University notes 
# theme:
#   name: material



#   font:
#     text: Roboto
#     code: Roboto Mono

#   features:
#     - content.tooltips
#     #- navigation.sections
#     - navigation.tabs
#     - navigation.top
#     - navigation.footer
#     - navigation.indexes
#     - navigation.tracking
#     #- navigation.expand
#     - navigation.path  
#     - toc.follow
#     - search.suggest
#     - search.highlight
#     - search.share
#     - content.tabs.link
#     - content.code.annotate
#     - content.code.copy
#     - content.footnote.tooltips

# markdown_extensions:
#   - footnotes
#   - pymdownx.highlight:
#       anchor_linenums: true
#       line_spans: __span
#       pygments_lang_class: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences
#   - attr_list
#   - md_in_html
#   - attr_list
#   - md_in_html
  

# # nav:
# #   - Strona główna: index.md
# #   - gRPC in Go/Java: grpc-go-java

# extra_css:
#   - stylesheets/extra.css

site_name: University notes
site_author: pawlowiczf
site_description: >-
  Notes

repo_name: documentation-notes-site
repo_url: https://github.com/pawlowiczf/documentation-notes-site


theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.tooltips
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.path  
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips

markdown_extensions:
  - footnotes
  - meta
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.tasklist
  - pymdownx.smartsymbols
  - attr_list
  - md_in_html

nav:
  - "": index.md

  - gRPC in Go/Java: 
    - gRPC setup in Go: grpc-go-java/notes1.md
    - gRPC setup in Java: grpc-go-java/notes2.md
    - Serialization - Go: grpc-go-java/notes3.md
    - Serialization - Java: grpc-go-java/notes4.md
    - Unary RPC - Go: grpc-go-java/notes5.md
    - Unary RPC - Java: grpc-go-java/notes6.md

  - Java/Spring/Hibernate:
    - Java/Spring/Hibernate: java-hibernate-spring/index.md
    - Databases: 
        - Content: java-hibernate-spring/db/index.md
        - Basic database operations/connections: java-hibernate-spring/db/notes1.md
        - Hibernate: java-hibernate-spring/db/notes2.md
        - Transactions: java-hibernate-spring/db/notes3.md
        - H2 database: java-hibernate-spring/db/notes4.md
    - Spring: 
        - Content: java-hibernate-spring/spring/index.md
        - Spring Boot: java-hibernate-spring/spring/spring_boot.md 
        - Spring Core: java-hibernate-spring/spring/spring_core.md 
        - Spring Hibernate: java-hibernate-spring/spring//spring_hibernate.md 
        - Spring REST: java-hibernate-spring/spring/spring_rest.md 
        - Spring Exceptions: java-hibernate-spring/spring/4_spring_exceptions.md
        - Spring REST Data: java-hibernate-spring/spring/5_spring_rest_data.md 
        - Swagger: java-hibernate-spring/spring/6_swagger.md
    - Spring security:
        - Content: java-hibernate-spring/spring-security/index.md
        - Spring Security Start: java-hibernate-spring/spring-security/1_spring_security.md

  - Go:
    - Go: go/index.md
    - Basics:
      - Content: go/basics/index.md
      - Net/HTTP: go/basics/1_net_http.md
  - Rust:
    - Rust: rust/index.md 
    - Basics:
      - Ownership: rust/basics/notes1.md
      - Object oriented programming: rust/basics/notes2.md
      - Generics/Pointers: rust/basics/notes3.md 
      - Lifespan: rust/basics/notes4.md
      - Enums: rust/basics/notes5.md 
      - Error handling: rust/basics/notes6.md
      - Collections: rust/basics/notes7.md 
      
  - DevOps:
    - DevOps: devops/index.md 
    - Jenkins:
      - Basic configuration: devops/jenkins/notes1.md 
    - Docker:
      - Basics: devops/docker/notes1.md 
      - Docker Compose : devops/docker/notes2.md     
    - Kubernetes:
      - Basic commands: devops/kubernetes/notes1.md

  - Network:
    - Network: network/index.md
    - Firewalls: network/bsk/notes1.md 
    - Private vlans/HSRP: network/bsk/notes2.md 
    - GLBP: network/bsk/notes3.md
    - Remote access: network/bsk/notes4.md
    - Other: network/bsk/notes5.md
  
  - Erlang:
    - OTP: erlang/otp/notes1.md 
    - 1: erlang/otp/notes2.md

  - Scala:
    - "": scala/index.md
    - Advanced concepts:
      - Syntax sugar: scala/advanced/notes1.md 
      - Pattern Matching: scala/advanced/notes2.md

  - Distributed Systems:
    - Kafka: distributed-systems/kafka/notes1.md 
extra_css:
  - stylesheets/extra.css
