name: ecmsp-dev

services:
    product-service-db-dev:
        image: postgres:15-alpine
        container_name: product-service-db-dev
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s

        ports:
            - "5432:5432"
        volumes:
            - product-service-db-dev:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        secrets:
            - product-service-db-password
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_DB=product-service-db
            - POSTGRES_PASSWORD_FILE=/run/secrets/product-service-db-password
        env_file:
            -
                path: ./database-env.txt
                required: false

    kafka:
        image: apache/kafka:3.7.0
        container_name: broker
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,EXTERNAL://localhost:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        ports:
            - "9094:9094"
        healthcheck:
            test:
              [
                  "CMD-SHELL",
                  "./opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1",
              ]
            interval: 10s
            timeout: 10s
            retries: 5

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        ports:
            - "8088:8080"
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
            KAFKA_CLUSTERS_0_READONLY: "false"
            # KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
        depends_on:
            kafka:
                condition: service_healthy

volumes:
    product-service-db-dev:

secrets:
    product-service-db-password:
        file: ./database-password.txt